Feat/scheduled events (#272)
* fix(audit): fix a weird type

* refactor(audit): rejig stuff

helps to be lexiographical to satisfy pep8 a little more
(like audit_log is very formatted in the first place)

* feat(audit_enums): add the 3 new events

* chore(enent-enums): add the relevant enums

* chore(audit): add the other types and type-aliases

* fix(license): add for the main modules (shows in editors)

* chore(audit): add to TRANSFORMERS

* feat(http): add http routes for events

need to add return types as i need to make the event class

* chore(http): add return types for event methods

* chore(types): add TypedDIct's for Event classes

* chore(scheduled-events): add event and metadata

add EntityMetadata class and start ScheduledEvent

* perf(entitymetadata): allow for user set of metadata

changed for inevitably when discord causes breaking changes
without bumping the version

* perf(http): more consistent

* perf(metadata): forgor :skull: that locatuon may be NoneType

* refactor(events): change for useability n stuff

* chore(events): add basic edit method

* feat(intents): add flag value for events

* fix(http): theyre query params my god

* feat(events): add iterator and guild.fetch_events

* fix(guild): return type is an iterator now

* feat(guild): fetch event method

* fix(events): wrong function name

* feat(guild): guild.create_event

* feat(event-users): fetch_members with an iterator

add
event.fetch_users
class EventUser
class EventUserIterator

* fix: add to __all__ and fix import

* fix: i still cant do this

* fix(doc-compile): i seem to have forgor ten to remove that

* fix(events): proper repr, not showing privates

* fix(events): not a fix, this is messy to account for no intents

if cache enabled, try to get member
if not, create member
if intents none also create member

* refactor: *event* -> scheduledevent*

EventStatus -> ScheduledEventStatus etc

* chore: more changes from last cmt

* feat(events): implement caching

* feat(events): add dispatching of events

* refactor(guild): i forgot to rename here, fix attr error too

* fix: vsc wont show it doesnt exist

* fix: default to 0 if its None so int() is happy

* fix: will this work now or what

* fix: just a comma :what:

* fix: everything

* fix: repr looks less messy

* fix: my god

* fix: another rename to scheduled_event

* fix: huh

* fix: undefined error

* fix: maybe?

* fix(state): has to be an int of course

* docs: add docs for scheduled events

* docs(?): add to codeowners

* fix: how did i forget to await

* fix: forgot to await here too

* feat(events): add default privacy level and force required

* fix: that broke everything

* fix: entitytype is also required and discord 500's w/o lmao

nextcord.errors.discordservererror: 500 internal server error (error code: 0): 500:
 internal server error

:trollage:

* fix: forgor bracket

* refactor(entitytype): -> scheduledevent.. +license

* chore: i seem to have forgotten to replace

* refactor: rename guild internal methods

* chore(guild): add typings

* feat(scheduled): new internal meths to prep for 2 new gateway events

* chore(scheduled): new dispatched scheduled events ... events

* docs(scheduled): add gateway event docs for all 5 new events

* fix(events): make the event param user

* fix(logging): fix logging typo

* docs(events): fix a few other minor issues

* fix(event): forgor to add to cache on event create

* chore(events): hang on what was my past commit then

* fix(events): forgor :skull: to add to slots, also integer id, also repr

* fix(events): add user to event cache

* feat(converters): add a ScheduledEventConverter

* fix(converters): its already compiled

* fix: oh yeah remove the copilot stuff :shh:

* fix(converter): remove past stuff

* feat(converters): match events/guildid/eventid url

* docs(converter): add docs to scheduledeventconverter

* perf(events): skelmis review points

* feat(events): add reason param to create and edit event

* fix(state): rename to proper method

* fix(docs): accident :skull:

* fix: attributeerror solved i hope

Co-authored-by: vcokltfre <vcokltfre@gmail.com>