fix: entitytype is also required and discord 500's w/o lmao
nextcord.errors.discordservererror: 500 internal server error (error code: 0): 500:
 internal server error

:trollage: